In [1]:
sum([1,2,3])

6

In [2]:
import numpy as np

In [3]:
X=np.array([[1,0,1],[2,2,2]]) 


In [4]:
X

array([[1, 0, 1],
       [2, 2, 2]])

In [5]:
X[0:2,2]

array([1, 2])

In [6]:
X=np.array([[1,0],[0,1]]) 
Y=np.array([[2,1],[1,2]]) 
Z=np.dot(X,Y) 
Z


array([[2, 1],
       [1, 2]])

In [9]:
a=np.array([-1,1]) 
b=np.array([1,1]) 
c=np.dot(a,b) 
c

np.int64(0)

In [10]:
X=np.array([[1,0],[0,1]])
Y=np.array([[2,2],[2,2]]) 
Z=np.dot(X,Y) 
Z

array([[2, 2],
       [2, 2]])